### ISSUE TITLE
Trained weights from darknet

### ISSUE THREAD

**Issue by tuanmonkeyy** [chumingqian/Model_Compression_For_YOLOV3-V4#10]
Hello, I trained YOLOv4 on my custom dataset using darknet and have a weights file, is there anyway I use this .weights file to prune using this repos without needing to retrain? Thank you very much

**Comment by chumingqian** [comment]
Before  prune the network, our method  need  retrain  on your custom dataset  so that the pruned network   can recover the  accuracy  by fine tuning the purned network.

However,  if  your  detection  task  is  easy , such as   only  one class  need to  detection,  if  you can try it without retrain,  but also  need  retrian  the pruned  network on your dataset.
